version: "3.8"

services:
  airflow-webserver:
    image: apache/airflow:2.9.0-python3.10
    container_name: airflow-webserver
    ports:
      - "8081:8080"
    command: webserver
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PROJECT_ROOT=/workspace
    volumes:
      - "../../:/workspace"
      - "./gemini_extraction_dag.py:/opt/airflow/dags/gemini_extraction_dag.py"
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    image: apache/airflow:2.9.0-python3.10
    container_name: airflow-scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PROJECT_ROOT=/workspace
    volumes:
      - "../../:/workspace"
      - "./gemini_extraction_dag.py:/opt/airflow/dags/gemini_extraction_dag.py"
